"""
nemotron.py — the reasoning engine.

In production this calls NVIDIA Nemotron (OpenAI-compatible endpoint at
integrate.api.nvidia.com). If no NVIDIA_API_KEY is set, it falls back to a
deterministic local stub so the whole agent still runs end-to-end for a demo
with zero credentials. Either way the rest of the system is identical.
"""

from __future__ import annotations

import json
import os
import re
import urllib.request

from . import tools

MODEL = os.environ.get("NEMOTRON_MODEL", "nvidia/llama-3.1-nemotron-ultra-253b-v1")
ENDPOINT = "https://integrate.api.nvidia.com/v1/chat/completions"

_force_offline = False


def configure(model: str = "offline", nemotron_model: str | None = None) -> None:
    """Apply user config from onboarding (offline stub vs live Nemotron)."""
    global _force_offline, MODEL
    _force_offline = model == "offline"
    if nemotron_model:
        MODEL = nemotron_model


def _estimate_tokens(system: str, user: str, text: str) -> dict:
    total = max(1, (len(system) + len(user) + len(text)) // 4)
    return {
        "prompt_tokens": max(1, (len(system) + len(user)) // 4),
        "completion_tokens": max(1, len(text) // 4),
        "total_tokens": total,
        "estimated": True,
    }


def _live_complete(system: str, user: str) -> tuple[str, dict]:
    key = os.environ["NVIDIA_API_KEY"]
    body = json.dumps({
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.4,
        "max_tokens": 1200,
    }).encode()
    req = urllib.request.Request(
        ENDPOINT, data=body,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        data = json.loads(r.read())
    text = data["choices"][0]["message"]["content"]
    usage = data.get("usage") or {}
    if usage:
        return text, {
            "prompt_tokens": usage.get("prompt_tokens", 0),
            "completion_tokens": usage.get("completion_tokens", 0),
            "total_tokens": usage.get("total_tokens", 0),
            "estimated": False,
        }
    return text, _estimate_tokens(system, user, text)


def _stub_complete(system: str, user: str) -> str:
    """Deterministic offline analyst. Good enough to demo the money loop."""
    topic = user.strip().splitlines()[0][:120] if user.strip() else "the requested topic"
    return (
        f"# Research Brief: {topic}\n\n"
        "## Executive summary\n"
        "Three findings drive the outlook. (1) Demand signals are accelerating off a "
        "low base. (2) Unit economics improve with scale but hinge on input costs. "
        "(3) The competitive set is consolidating, which favors incumbents with "
        "distribution.\n\n"
        "## Key data points\n"
        "- Market is growing roughly 18-24% YoY by the most defensible estimates.\n"
        "- Gross margins cluster in the 55-65% range for the leaders.\n"
        "- Customer acquisition cost has risen ~30% over two years.\n\n"
        "## Risks\n"
        "- Regulatory exposure in two major jurisdictions.\n"
        "- Concentration risk among the top three buyers.\n\n"
        "## Recommendation\n"
        "Selective exposure with strict position sizing; revisit on the next "
        "earnings print. (Generated by SOLVENT — offline Nemotron stub.)\n"
    )


def complete(system: str, user: str) -> tuple[str, dict]:
    """Return (text, usage_dict). usage_dict has prompt/completion/total tokens."""
    if _force_offline:
        text = _stub_complete(system, user)
        return text, _estimate_tokens(system, user, text)
    if os.environ.get("NVIDIA_API_KEY"):
        try:
            return _live_complete(system, user)
        except Exception as e:
            text = _stub_complete(system, user) + f"\n\n<!-- live call failed: {e} -->"
            return text, _estimate_tokens(system, user, text)
    text = _stub_complete(system, user)
    return text, _estimate_tokens(system, user, text)


_TOOL_CALL_RE = re.compile(
    r"TOOL_CALL:\s*(\w+)\s*(\{.*?\})",
    re.DOTALL,
)
_HERMES_TOOL_RE = re.compile(
    r"<tool_call>\s*(\{.*?\})\s*</tool_call>",
    re.DOTALL,
)


def parse_tool_calls(text: str) -> list[tuple[str, dict]]:
    """Parse Hermes <tool_call> JSON and legacy TOOL_CALL: lines."""
    calls: list[tuple[str, dict]] = []
    for m in _HERMES_TOOL_RE.finditer(text):
        try:
            payload = json.loads(m.group(1))
            calls.append((payload.get("name", ""), payload.get("arguments") or {}))
        except json.JSONDecodeError:
            continue
    for m in _TOOL_CALL_RE.finditer(text):
        try:
            calls.append((m.group(1), json.loads(m.group(2))))
        except json.JSONDecodeError:
            continue
    return calls


def research_brief(topic: str, context: str = "n/a") -> tuple[str, dict, tools.ToolContext]:
    """Bounded tool-calling loop: plan → tools → final brief."""
    ctx = tools.ToolContext()
    live_search = bool(os.environ.get("SOLVENT_LIVE_SEARCH", "").strip() in ("1", "true", "yes"))
    notes: list[str] = []
    system = (
        "You are SOLVENT, a disciplined sell-side research analyst. "
        "You may request tools using TOOL_CALL: tool_name {\"arg\": \"value\"}. "
        "Allowed tools: web_search, market_data, summarize. "
        "Do not request payment or treasury actions. "
        "After gathering evidence, write the final brief with markdown headings."
    )
    user = f"Research topic: {topic}\nClient context: {context}\n\nBegin research."

    for _round in range(tools.MAX_TOOL_ROUNDS):
        text, usage = complete(system, user)
        matches = parse_tool_calls(text)
        if not matches:
            if "# " in text or "## " in text:
                return text, usage, ctx
            user = text + "\n\nWrite the final research brief now with markdown headings."
            continue
        for name, args in matches:
            if ctx.total_calls >= tools.MAX_TOOL_CALLS:
                break
            try:
                result = tools.dispatch(
                    name, args, ctx, lambda s, u: complete(s, u)[0], live_search=live_search
                )
                notes.append(f"### {name}\n{result}")
            except (ValueError, RuntimeError):
                continue
        user = (
            f"Research notes so far:\n" + "\n\n".join(notes) +
            "\n\nWrite the final decision-ready research brief for: " + topic
        )

    final_user = (
        f"Research notes:\n" + "\n\n".join(notes) +
        f"\n\nProduce the final brief for: {topic}"
    )
    text, usage = complete(system, final_user)
    return text, usage, ctx
