"""
nemotron.py — the reasoning engine.

In production this calls NVIDIA Nemotron (OpenAI-compatible endpoint at
integrate.api.nvidia.com). If no NVIDIA_API_KEY is set, it falls back to a
deterministic local stub so the whole agent still runs end-to-end for a demo
with zero credentials. Either way the rest of the system is identical.
"""

from __future__ import annotations

import os
import json
import urllib.request


MODEL = os.environ.get("NEMOTRON_MODEL", "nvidia/llama-3.1-nemotron-ultra-253b-v1")
ENDPOINT = "https://integrate.api.nvidia.com/v1/chat/completions"

_force_offline = False


def configure(model: str = "offline", nemotron_model: str | None = None) -> None:
    """Apply user config from onboarding (offline stub vs live Nemotron)."""
    global _force_offline, MODEL
    _force_offline = model == "offline"
    if nemotron_model:
        MODEL = nemotron_model


def _live_complete(system: str, user: str) -> str:
    key = os.environ["NVIDIA_API_KEY"]
    body = json.dumps({
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.4,
        "max_tokens": 1200,
    }).encode()
    req = urllib.request.Request(
        ENDPOINT, data=body,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        data = json.loads(r.read())
    return data["choices"][0]["message"]["content"]


def _stub_complete(system: str, user: str) -> str:
    """Deterministic offline analyst. Good enough to demo the money loop."""
    topic = user.strip().splitlines()[0][:120] if user.strip() else "the requested topic"
    return (
        f"# Research Brief: {topic}\n\n"
        "## Executive summary\n"
        "Three findings drive the outlook. (1) Demand signals are accelerating off a "
        "low base. (2) Unit economics improve with scale but hinge on input costs. "
        "(3) The competitive set is consolidating, which favors incumbents with "
        "distribution.\n\n"
        "## Key data points\n"
        "- Market is growing roughly 18-24% YoY by the most defensible estimates.\n"
        "- Gross margins cluster in the 55-65% range for the leaders.\n"
        "- Customer acquisition cost has risen ~30% over two years.\n\n"
        "## Risks\n"
        "- Regulatory exposure in two major jurisdictions.\n"
        "- Concentration risk among the top three buyers.\n\n"
        "## Recommendation\n"
        "Selective exposure with strict position sizing; revisit on the next "
        "earnings print. (Generated by SOLVENT — offline Nemotron stub.)\n"
    )


def complete(system: str, user: str) -> tuple[str, int]:
    """Return (text, tokens_used_estimate)."""
    if _force_offline:
        text = _stub_complete(system, user)
        tokens = max(1, (len(system) + len(user) + len(text)) // 4)
        return text, tokens
    if os.environ.get("NVIDIA_API_KEY"):
        try:
            text = _live_complete(system, user)
        except Exception as e:  # network/key issues -> never break the demo
            text = _stub_complete(system, user) + f"\n\n<!-- live call failed: {e} -->"
    else:
        text = _stub_complete(system, user)
    tokens = max(1, (len(system) + len(user) + len(text)) // 4)
    return text, tokens
