"""
pricing.py — the margin gate. SOLVENT's core economic discipline.

Before accepting any job, the agent estimates what the job will COST it to
fulfil (compute + data + SaaS) and what it can PRICE the job at. If the
projected margin does not clear the floor, the agent declines the work.

This is the feature that makes SOLVENT a *business* and not just a bot: it is
structurally incapable of working at a loss.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Tuple


# Estimated cost of each resource the analyst might consume, in cents.
# These are the prices SOLVENT pays its own vendors (see stripe_client.spend).
RESOURCE_COSTS_CENTS: Dict[str, int] = {
    "nemotron_tokens_per_1k": 30,    # NVIDIA Nemotron inference
    "market_data_call": 120,         # market-data-api per pull
    "web_search_call": 8,            # web-search-api per query
    "pdf_render": 40,                # pdf-render-saas per report
    "email_send": 5,                 # email-delivery-saas per delivery
}


@dataclass
class Quote:
    """Represents a job quote generated by the margin gate.

    Attributes:
        price_cents: The price quoted to the client (equal to client's budget).
        est_cost_cents: The estimated fulfillment cost in cents.
        margin_cents: The projected profit margin in cents.
        margin_pct: The projected profit margin percentage.
        accept: True if the job is accepted, False if declined.
        reason: Explanatory text for the decision.
        cost_breakdown: Itemized dictionary of estimated vendor costs.
    """
    price_cents: int
    est_cost_cents: int
    margin_cents: int
    margin_pct: float
    accept: bool
    reason: str
    cost_breakdown: Dict[str, int]


@dataclass
class PricingPolicy:
    """Pricing rules governing the margin gate.

    Attributes:
        margin_floor_pct: The minimum profit margin required to accept a job.
        min_price_cents: The minimum price (order size) in cents for any job.
    """
    margin_floor_pct: float = 35.0     # refuse jobs under this projected margin
    min_price_cents: int = 1_500       # never sell a report under $15


def get_resource_costs() -> Dict[str, int]:
    """Return effective resource costs, applying overrides from .solvent/pricing_overrides.json if present."""
    from pathlib import Path
    import json
    costs = dict(RESOURCE_COSTS_CENTS)
    override_path = Path(".solvent/pricing_overrides.json")
    if override_path.is_file():
        try:
            overrides = json.loads(override_path.read_text(encoding="utf-8"))
            if isinstance(overrides, dict):
                for k, v in overrides.items():
                    if k in costs and isinstance(v, (int, float)):
                        costs[k] = int(v)
        except (json.JSONDecodeError, OSError):
            pass
    return costs


def estimate_cost(job: Dict[str, Any]) -> Tuple[int, Dict[str, int]]:
    """Estimate fulfilment cost from the job's declared complexity."""
    costs = get_resource_costs()
    tokens_k = job.get("est_tokens", 8_000) / 1_000
    breakdown = {
        "nemotron_inference": round(tokens_k * costs["nemotron_tokens_per_1k"]),
        "market_data": job.get("market_data_calls", 2) * costs["market_data_call"],
        "web_search": job.get("web_search_calls", 6) * costs["web_search_call"],
        "pdf_render": costs["pdf_render"],
        "email_send": costs["email_send"],
    }
    return sum(breakdown.values()), breakdown


def quote(job: Dict[str, Any], policy: PricingPolicy | None = None) -> Quote:
    """Evaluate if a job's budget is acceptable according to the pricing policy.

    The budget is treated as the target price. The function checks whether this price
    satisfies the minimum price requirement and the margin floor.

    Args:
        job: A dictionary containing the job details (e.g. budget_cents).
        policy: The pricing policy to apply. Defaults to a new PricingPolicy instance.

    Returns:
        A Quote object indicating whether the job was accepted or rejected.
    """
    applied_policy = policy or PricingPolicy()
    est_cost, breakdown = estimate_cost(job)

    # We can never charge more than the customer is willing to pay, so the
    # budget IS the price. The gate then decides whether that price clears
    # both the minimum order size and the margin floor.
    budget = job.get("budget_cents", 0)
    price = budget

    margin = price - est_cost
    margin_pct = round(100 * margin / price, 1) if price else -100.0

    if budget < applied_policy.min_price_cents:
        return Quote(
            price, est_cost, margin, margin_pct, False,
            f"order ${budget/100:.0f} below minimum order size ${applied_policy.min_price_cents/100:.0f}",
            breakdown
        )
    if budget < est_cost:
        return Quote(
            price, est_cost, margin, margin_pct, False,
            "customer budget below fulfilment cost", breakdown
        )
    if margin_pct < applied_policy.margin_floor_pct:
        return Quote(
            price, est_cost, margin, margin_pct, False,
            f"projected margin {margin_pct}% below floor {applied_policy.margin_floor_pct}%",
            breakdown
        )
    return Quote(price, est_cost, margin, margin_pct, True, "accepted", breakdown)

